home:
  title: CIS 547 - Software Analysis
  url: /index.html
navigation:
  - title: Schedule
    url: /schedule.html
  - title: Labs
    url: /labs.html
  - title: Lectures
    url: /lectures.html
  - title: Staff
    url: /staff.html


theme: jekyll-theme-cayman