title: "CIS 547 - Software Analysis"
course: "CIS 547"
url: https://cis547.github.io/
navigation:
  - title: Labs
    url: /labs
  - title: Lectures
    url: /lectures
  - title: Schedule
    url: /schedule
  - title: Staff
    url: /staff
collections:
  lectures:
    output: true
  labs:
    output: true
theme: jekyll-theme-cayman
