title: "CIS 5470 - Software Analysis"
course: "CIS 5470"
tagline: "Spring 2025 • University of Pennsylvania"
description: "A rigorous introduction to software analysis techniques for finding bugs, ensuring security, and improving software reliability"
author:
  name: Dr. Mayur Naik
  email: mhnaik@seas.upenn.edu
baseurl: "" 
url: "https://cis547.github.io"

# Theme
remote_theme: just-the-docs/just-the-docs@v0.10.1

# Navigation uses parent/child structure instead of collections

# Just the Class theme settings
heading_anchors: true
permalink: pretty
aux_links:
  Ed Discussion:
    - 'https://edstem.org/'
  Canvas:
    - 'https://canvas.upenn.edu/'
  Gradescope:
    - 'https://gradescope.com/'
aux_links_new_tab: true
footer_content: "&copy; 2025 University of Pennsylvania. All rights reserved."

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

last_edit_timestamp: false
gh_edit_link: false

# Color scheme
color_scheme: cis547

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10

# Using theme default content width

# Navigation
nav_enabled: true
nav_sort: case_insensitive

# Compression settings
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
